steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file
      - backend/Dockerfile
      - --tag
      - ${_IMAGE}
      - .
images:
  - ${_IMAGE}
substitutions:
  _IMAGE: us-central1-docker.pkg.dev/acp-hackathon-2026-505906/acp/agent-control-plane:latest
options:
  logging: CLOUD_LOGGING_ONLY
